apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: sample-app-config
    literals:
      - TEXT=sample-app (kustomize/base)
