apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-app
  ports:
    - name: http
      port: 80
      targetPort: http

