apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    app.kubernetes.io/name: sample-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: sample-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

